// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Tela_Inicial.h"
#include "ui_Selecao_de_Modo.h"
#include "ui_Modo_Registro.h"
#include "ui_Novo_Registro.h"
#include "ui_Dashboard.h"
#include "ui_Tela_Instrumento.h"
#include "ui_Tela_Termometro.h"
#include "ui_Tela_Oximetro.h"
#include "ui_GSR.h"
#include "ui_ECG.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Blink_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mbi_logo_png);    // assets/MBI_logo.png
LV_IMG_DECLARE(ui_img_586855341);    // assets/icons8-planilha-50.png
LV_IMG_DECLARE(ui_img_939456327);    // assets/icons8-estetoscópio-50.png
LV_IMG_DECLARE(ui_img_1725504982);    // assets/icons8-ponto-final-15.png
LV_IMG_DECLARE(ui_img_1561148902);    // assets/icons8-soma-30.png
LV_IMG_DECLARE(ui_img_587847134);    // assets/icons8-relógio-20.png
LV_IMG_DECLARE(ui_img_1635948304);    // assets/icons8-termômetro-40.png
LV_IMG_DECLARE(ui_img_652512494);    // assets/icons8-forward-20.png
LV_IMG_DECLARE(ui_img_1680349653);    // assets/icons8-coração-com-pulso-40 (1).png
LV_IMG_DECLARE(ui_img_134478313);    // assets/icons8-pulsação-40.png
LV_IMG_DECLARE(ui_img_gsr_png);    // assets/gsr.png
LV_IMG_DECLARE(ui_img_177543304);    // assets/risk (1).png
LV_IMG_DECLARE(ui_img_96564182);    // assets/icons8-círculo-preenchido-64.png
LV_IMG_DECLARE(ui_img_141844619);    // assets/icons8-gostar-20.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
