// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"
#include "../ui_event_bridge.h"

lv_obj_t * ui_Carregar_Dados = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_backButton4 = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions
void ui_event_backButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Modo_Registro, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Modo_Registro_screen_init);
    }
}

// build funtions

void ui_Carregar_Dados_screen_init(void)
{
    ui_Carregar_Dados = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Carregar_Dados, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Carregar_Dados, lv_color_hex(0x003F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Carregar_Dados, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Carregar_Dados);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Carregando dados..."); // Texto inicial
    lv_obj_set_width(ui_Label9, 300); // Define uma largura para quebra de linha
    lv_label_set_long_mode(ui_Label9, LV_LABEL_LONG_WRAP); // Permite quebra de linha

    app_load_data_preview(ui_Label9);

    ui_backButton4 = lv_btn_create(ui_Carregar_Dados);
    lv_obj_set_width(ui_backButton4, 90);
    lv_obj_set_height(ui_backButton4, 35);
    lv_obj_set_x(ui_backButton4, -110);
    lv_obj_set_y(ui_backButton4, 95);
    lv_obj_set_align(ui_backButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton4, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_backButton4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Voltar");

    lv_obj_add_event_cb(ui_backButton4, ui_event_backButton4, LV_EVENT_ALL, NULL);

}

void ui_Carregar_Dados_screen_destroy(void)
{
    if(ui_Carregar_Dados) lv_obj_del(ui_Carregar_Dados);

    // NULL screen variables
    ui_Carregar_Dados = NULL;
    ui_Label9 = NULL;
    ui_backButton4 = NULL;
    ui_Label15 = NULL;

}
