// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_COMP_COMBARRASTATUS_H
#define _UI_COMP_COMBARRASTATUS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ComBarraStatus
#define UI_COMP_COMBARRASTATUS_COMBARRASTATUS 0
#define UI_COMP_COMBARRASTATUS_LABELHORA 1
#define UI_COMP_COMBARRASTATUS_LABELTITULO 2
#define UI_COMP_COMBARRASTATUS_REC_DOT 3
#define _UI_COMP_COMBARRASTATUS_NUM 4
lv_obj_t * ui_ComBarraStatus_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
