// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_COMP_CARDBASE2_H
#define _UI_COMP_CARDBASE2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Cardbase2
#define UI_COMP_CARDBASE2_CARDBASE2 0
#define UI_COMP_CARDBASE2_BARRA_COR3 1
#define UI_COMP_CARDBASE2_LBL_TITULO3 2
#define UI_COMP_CARDBASE2_IMG_ICONE3 3
#define UI_COMP_CARDBASE2_IMG_SETA3 4
#define _UI_COMP_CARDBASE2_NUM 5
lv_obj_t * ui_Cardbase2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
