// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

// COMPONENT Cardbase2

lv_obj_t * ui_Cardbase2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Cardbase2;
    cui_Cardbase2 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Cardbase2);
    lv_obj_set_width(cui_Cardbase2, 280);
    lv_obj_set_height(cui_Cardbase2, 50);
    lv_obj_set_align(cui_Cardbase2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Cardbase2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Cardbase2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Cardbase2, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Cardbase2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Barra_Cor3;
    cui_Barra_Cor3 = lv_obj_create(cui_Cardbase2);
    lv_obj_set_width(cui_Barra_Cor3, 10);
    lv_obj_set_height(cui_Barra_Cor3, lv_pct(142));
    lv_obj_set_align(cui_Barra_Cor3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Barra_Cor3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Barra_Cor3, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Barra_Cor3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Barra_Cor3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Lbl_Titulo3;
    cui_Lbl_Titulo3 = lv_label_create(cui_Cardbase2);
    lv_obj_set_width(cui_Lbl_Titulo3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Lbl_Titulo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Lbl_Titulo3, 70);
    lv_obj_set_y(cui_Lbl_Titulo3, 0);
    lv_obj_set_align(cui_Lbl_Titulo3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Lbl_Titulo3, "Termometro");

    lv_obj_t * cui_Img_Icone3;
    cui_Img_Icone3 = lv_img_create(cui_Cardbase2);
    lv_obj_set_width(cui_Img_Icone3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Img_Icone3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Img_Icone3, 20);
    lv_obj_set_y(cui_Img_Icone3, 0);
    lv_obj_set_align(cui_Img_Icone3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Img_Icone3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Img_Icone3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_Img_Icone3, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_Img_Icone3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Img_Seta3;
    cui_Img_Seta3 = lv_img_create(cui_Cardbase2);
    lv_obj_set_width(cui_Img_Seta3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Img_Seta3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Img_Seta3, -10);
    lv_obj_set_y(cui_Img_Seta3, 0);
    lv_obj_set_align(cui_Img_Seta3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Img_Seta3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Img_Seta3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CARDBASE2_NUM);
    children[UI_COMP_CARDBASE2_CARDBASE2] = cui_Cardbase2;
    children[UI_COMP_CARDBASE2_BARRA_COR3] = cui_Barra_Cor3;
    children[UI_COMP_CARDBASE2_LBL_TITULO3] = cui_Lbl_Titulo3;
    children[UI_COMP_CARDBASE2_IMG_ICONE3] = cui_Img_Icone3;
    children[UI_COMP_CARDBASE2_IMG_SETA3] = cui_Img_Seta3;
    lv_obj_add_event_cb(cui_Cardbase2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Cardbase2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Cardbase2_create_hook(cui_Cardbase2);
    return cui_Cardbase2;
}

