// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

// COMPONENT Termometro

lv_obj_t * ui_Termometro_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Termometro;
    cui_Termometro = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Termometro);
    lv_obj_set_width(cui_Termometro, 280);
    lv_obj_set_height(cui_Termometro, 50);
    lv_obj_set_align(cui_Termometro, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Termometro, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Termometro, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Termometro, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Termometro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Barra_Cor;
    cui_Barra_Cor = lv_obj_create(cui_Termometro);
    lv_obj_set_width(cui_Barra_Cor, 10);
    lv_obj_set_height(cui_Barra_Cor, lv_pct(142));
    lv_obj_set_align(cui_Barra_Cor, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Barra_Cor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Barra_Cor, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Barra_Cor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Barra_Cor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Lbl_Titulo;
    cui_Lbl_Titulo = lv_label_create(cui_Termometro);
    lv_obj_set_width(cui_Lbl_Titulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Lbl_Titulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Lbl_Titulo, 50);
    lv_obj_set_y(cui_Lbl_Titulo, 0);
    lv_obj_set_align(cui_Lbl_Titulo, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Lbl_Titulo, "Termometro");

    lv_obj_t * cui_Img_Icone;
    cui_Img_Icone = lv_img_create(cui_Termometro);
    lv_obj_set_width(cui_Img_Icone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Img_Icone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Img_Icone, 10);
    lv_obj_set_y(cui_Img_Icone, 0);
    lv_obj_set_align(cui_Img_Icone, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Img_Icone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Img_Icone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_Img_Icone, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_Img_Icone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Img_Seta;
    cui_Img_Seta = lv_img_create(cui_Termometro);
    lv_obj_set_width(cui_Img_Seta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Img_Seta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Img_Seta, -10);
    lv_obj_set_y(cui_Img_Seta, 0);
    lv_obj_set_align(cui_Img_Seta, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Img_Seta, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Img_Seta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TERMOMETRO_NUM);
    children[UI_COMP_TERMOMETRO_TERMOMETRO] = cui_Termometro;
    children[UI_COMP_TERMOMETRO_BARRA_COR] = cui_Barra_Cor;
    children[UI_COMP_TERMOMETRO_LBL_TITULO] = cui_Lbl_Titulo;
    children[UI_COMP_TERMOMETRO_IMG_ICONE] = cui_Img_Icone;
    children[UI_COMP_TERMOMETRO_IMG_SETA] = cui_Img_Seta;
    lv_obj_add_event_cb(cui_Termometro, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Termometro, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Termometro_create_hook(cui_Termometro);
    return cui_Termometro;
}

