// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_COMP_TERMOMETRO_H
#define _UI_COMP_TERMOMETRO_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Termometro
#define UI_COMP_TERMOMETRO_TERMOMETRO 0
#define UI_COMP_TERMOMETRO_BARRA_COR 1
#define UI_COMP_TERMOMETRO_LBL_TITULO 2
#define UI_COMP_TERMOMETRO_IMG_ICONE 3
#define UI_COMP_TERMOMETRO_IMG_SETA 4
#define _UI_COMP_TERMOMETRO_NUM 5
lv_obj_t * ui_Termometro_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
