// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

// COMPONENT ComBarraStatus

lv_obj_t * ui_ComBarraStatus_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ComBarraStatus;
    cui_ComBarraStatus = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ComBarraStatus, 330);
    lv_obj_set_height(cui_ComBarraStatus, 20);
    lv_obj_set_align(cui_ComBarraStatus, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(cui_ComBarraStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ComBarraStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ComBarraStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ComBarraStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelHora;
    cui_LabelHora = lv_label_create(cui_ComBarraStatus);
    lv_obj_set_width(cui_LabelHora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelHora, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelHora, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelHora, "00:00");
    lv_obj_set_style_text_color(cui_LabelHora, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelHora, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelHora, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelTitulo;
    cui_LabelTitulo = lv_label_create(cui_ComBarraStatus);
    lv_obj_set_width(cui_LabelTitulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelTitulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelTitulo, 10);
    lv_obj_set_y(cui_LabelTitulo, 0);
    lv_obj_set_align(cui_LabelTitulo, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_LabelTitulo, "MBI");

    lv_obj_t * cui_rec_dot;
    cui_rec_dot = lv_img_create(cui_ComBarraStatus);
    lv_img_set_src(cui_rec_dot, &ui_img_1725504982);
    lv_obj_set_width(cui_rec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_rec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_rec_dot, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_rec_dot, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_rec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_rec_dot, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_rec_dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_COMBARRASTATUS_NUM);
    children[UI_COMP_COMBARRASTATUS_COMBARRASTATUS] = cui_ComBarraStatus;
    children[UI_COMP_COMBARRASTATUS_LABELHORA] = cui_LabelHora;
    children[UI_COMP_COMBARRASTATUS_LABELTITULO] = cui_LabelTitulo;
    children[UI_COMP_COMBARRASTATUS_REC_DOT] = cui_rec_dot;
    lv_obj_add_event_cb(cui_ComBarraStatus, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ComBarraStatus, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ComBarraStatus_create_hook(cui_ComBarraStatus);
    return cui_ComBarraStatus;
}

