// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

void ui_comp_Cardbase2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ComBarraStatus_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Termometro_create_hook(lv_obj_t * comp)
{
}
