// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_LabelGSR;
lv_obj_t * uic_BTgsr;
lv_obj_t * uic_LabelBPM;
lv_obj_t * uic_BTbpm;
lv_obj_t * uic_LabelOxi;
lv_obj_t * uic_BTOxi;
lv_obj_t * uic_LabelTemp;
lv_obj_t * uic_BTtemp;
lv_obj_t * ui_Dashboard = NULL;
lv_obj_t * ui_ComBarraStatus6 = NULL;
lv_obj_t * ui_BTtemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_BTOxi = NULL;
lv_obj_t * ui_LabelOxi = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_BTbpm = NULL;
lv_obj_t * ui_LabelBPM = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_BTSalvar2 = NULL;
lv_obj_t * ui_LabelSalvar2 = NULL;
lv_obj_t * ui_BTgsr = NULL;
lv_obj_t * ui_LabelGSR = NULL;
lv_obj_t * ui_Label23 = NULL;
// event funtions
void ui_event_Dashboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_flag_modify(ui_comp_get_child(ui_ComStatusBar2, UI_COMP_COMBARRASTATUS_REC_DOT), LV_OBJ_FLAG_HIDDEN,
                        _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_BTtemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tela_Termometro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Termometro_screen_init);
    }
}

void ui_event_BTOxi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tela_Oximetro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Oximetro_screen_init);
    }
}

void ui_event_BTbpm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ECG, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ECG_screen_init);
    }
}

void ui_event_BTSalvar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Novo_Registro, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Novo_Registro_screen_init);
    }
}

void ui_event_BTgsr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GSR, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_GSR_screen_init);
    }
}

// build funtions

void ui_Dashboard_screen_init(void)
{
    ui_Dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ComBarraStatus6 = ui_ComBarraStatus_create(ui_Dashboard);
    lv_obj_set_x(ui_ComBarraStatus6, 0);
    lv_obj_set_y(ui_ComBarraStatus6, 0);

    ui_BTtemp = lv_btn_create(ui_Dashboard);
    lv_obj_set_width(ui_BTtemp, 150);
    lv_obj_set_height(ui_BTtemp, 70);
    lv_obj_set_x(ui_BTtemp, -78);
    lv_obj_set_y(ui_BTtemp, -60);
    lv_obj_set_align(ui_BTtemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTtemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTtemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTtemp, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_BTtemp);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "99");
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_BTtemp);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 30);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "°C");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTOxi = lv_btn_create(ui_Dashboard);
    lv_obj_set_width(ui_BTOxi, 150);
    lv_obj_set_height(ui_BTOxi, 70);
    lv_obj_set_x(ui_BTOxi, -78);
    lv_obj_set_y(ui_BTOxi, 15);
    lv_obj_set_align(ui_BTOxi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTOxi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTOxi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTOxi, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTOxi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOxi = lv_label_create(ui_BTOxi);
    lv_obj_set_width(ui_LabelOxi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOxi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOxi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOxi, "99");
    lv_obj_set_style_text_font(ui_LabelOxi, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_BTOxi);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 25);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "SpO2");

    ui_Label29 = lv_label_create(ui_BTOxi);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 30);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "%");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTbpm = lv_btn_create(ui_Dashboard);
    lv_obj_set_width(ui_BTbpm, 150);
    lv_obj_set_height(ui_BTbpm, 70);
    lv_obj_set_x(ui_BTbpm, 78);
    lv_obj_set_y(ui_BTbpm, -60);
    lv_obj_set_align(ui_BTbpm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTbpm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTbpm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTbpm, lv_color_hex(0x1FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTbpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBPM = lv_label_create(ui_BTbpm);
    lv_obj_set_width(ui_LabelBPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBPM, "99");
    lv_obj_set_style_text_font(ui_LabelBPM, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_BTbpm);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, 25);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "BPM");

    ui_BTSalvar2 = lv_btn_create(ui_Dashboard);
    lv_obj_set_width(ui_BTSalvar2, 205);
    lv_obj_set_height(ui_BTSalvar2, 43);
    lv_obj_set_x(ui_BTSalvar2, 0);
    lv_obj_set_y(ui_BTSalvar2, 85);
    lv_obj_set_align(ui_BTSalvar2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTSalvar2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTSalvar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTSalvar2, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTSalvar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSalvar2 = lv_label_create(ui_BTSalvar2);
    lv_obj_set_width(ui_LabelSalvar2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalvar2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSalvar2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalvar2, "PARAR GRAVACAO");

    ui_BTgsr = lv_btn_create(ui_Dashboard);
    lv_obj_set_width(ui_BTgsr, 150);
    lv_obj_set_height(ui_BTgsr, 70);
    lv_obj_set_x(ui_BTgsr, 78);
    lv_obj_set_y(ui_BTgsr, 14);
    lv_obj_set_align(ui_BTgsr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTgsr, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTgsr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTgsr, lv_color_hex(0xB800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTgsr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGSR = lv_label_create(ui_BTgsr);
    lv_obj_set_width(ui_LabelGSR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGSR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGSR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGSR, "99");
    lv_obj_set_style_text_font(ui_LabelGSR, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_BTgsr);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 25);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "GSR");

    lv_obj_add_event_cb(ui_BTtemp, ui_event_BTtemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTOxi, ui_event_BTOxi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTbpm, ui_event_BTbpm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTSalvar2, ui_event_BTSalvar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTgsr, ui_event_BTgsr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dashboard, ui_event_Dashboard, LV_EVENT_ALL, NULL);
    uic_BTtemp = ui_BTtemp;
    uic_LabelTemp = ui_LabelTemp;
    uic_BTOxi = ui_BTOxi;
    uic_LabelOxi = ui_LabelOxi;
    uic_BTbpm = ui_BTbpm;
    uic_LabelBPM = ui_LabelBPM;
    uic_BTgsr = ui_BTgsr;
    uic_LabelGSR = ui_LabelGSR;

}

void ui_Dashboard_screen_destroy(void)
{
    if(ui_Dashboard) lv_obj_del(ui_Dashboard);

    // NULL screen variables
    ui_Dashboard = NULL;
    ui_ComBarraStatus6 = NULL;
    uic_BTtemp = NULL;
    ui_BTtemp = NULL;
    uic_LabelTemp = NULL;
    ui_LabelTemp = NULL;
    ui_Label26 = NULL;
    uic_BTOxi = NULL;
    ui_BTOxi = NULL;
    uic_LabelOxi = NULL;
    ui_LabelOxi = NULL;
    ui_Label25 = NULL;
    ui_Label29 = NULL;
    uic_BTbpm = NULL;
    ui_BTbpm = NULL;
    uic_LabelBPM = NULL;
    ui_LabelBPM = NULL;
    ui_Label24 = NULL;
    ui_BTSalvar2 = NULL;
    ui_LabelSalvar2 = NULL;
    uic_BTgsr = NULL;
    ui_BTgsr = NULL;
    uic_LabelGSR = NULL;
    ui_LabelGSR = NULL;
    ui_Label23 = NULL;

}
