// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Dashboard
extern void ui_Dashboard_screen_init(void);
extern void ui_Dashboard_screen_destroy(void);
extern void ui_event_Dashboard(lv_event_t * e);
extern lv_obj_t * ui_Dashboard;
extern lv_obj_t * ui_ComBarraStatus6;
extern void ui_event_BTtemp(lv_event_t * e);
extern lv_obj_t * ui_BTtemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_Label26;
extern void ui_event_BTOxi(lv_event_t * e);
extern lv_obj_t * ui_BTOxi;
extern lv_obj_t * ui_LabelOxi;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label29;
extern void ui_event_BTbpm(lv_event_t * e);
extern lv_obj_t * ui_BTbpm;
extern lv_obj_t * ui_LabelBPM;
extern lv_obj_t * ui_Label24;
extern void ui_event_BTSalvar2(lv_event_t * e);
extern lv_obj_t * ui_BTSalvar2;
extern lv_obj_t * ui_LabelSalvar2;
extern void ui_event_BTgsr(lv_event_t * e);
extern lv_obj_t * ui_BTgsr;
extern lv_obj_t * ui_LabelGSR;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BTtemp;
extern lv_obj_t * uic_LabelTemp;
extern lv_obj_t * uic_BTOxi;
extern lv_obj_t * uic_LabelOxi;
extern lv_obj_t * uic_BTbpm;
extern lv_obj_t * uic_LabelBPM;
extern lv_obj_t * uic_BTgsr;
extern lv_obj_t * uic_LabelGSR;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

