// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_ECG_H
#define UI_ECG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ECG
extern void ui_ECG_screen_init(void);
extern void ui_ECG_screen_destroy(void);
extern lv_obj_t * ui_ECG;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ComBarraStatus3;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_LabelMedBPM2;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

