// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_ECG = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ComBarraStatus3 = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_LabelMedBPM2 = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions

// build funtions

void ui_ECG_screen_init(void)
{
    ui_ECG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ECG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_ECG);
    lv_obj_set_width(ui_Button7, 155);
    lv_obj_set_height(ui_Button7, 20);
    lv_obj_set_x(ui_Button7, -76);
    lv_obj_set_y(ui_Button7, -7);
    lv_obj_set_align(ui_Button7, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Voltar");

    ui_ComBarraStatus3 = ui_ComBarraStatus_create(ui_ECG);
    lv_obj_set_x(ui_ComBarraStatus3, 0);
    lv_obj_set_y(ui_ComBarraStatus3, 0);

    ui_Chart2 = lv_chart_create(ui_ECG);
    lv_obj_set_width(ui_Chart2, 220);
    lv_obj_set_height(ui_Chart2, 120);
    lv_obj_set_x(ui_Chart2, 0);
    lv_obj_set_y(ui_Chart2, -20);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 50);
    lv_chart_set_div_line_count(ui_Chart2, 10, 8);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x00FF31),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 0, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 0, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_ECG);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 50);
    lv_obj_set_y(ui_Label22, 65);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "BPM");

    ui_LabelMedBPM2 = lv_label_create(ui_ECG);
    lv_obj_set_width(ui_LabelMedBPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMedBPM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMedBPM2, 0);
    lv_obj_set_y(ui_LabelMedBPM2, 65);
    lv_obj_set_align(ui_LabelMedBPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMedBPM2, "99");
    lv_obj_set_style_text_color(ui_LabelMedBPM2, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMedBPM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMedBPM2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ECG);
    lv_img_set_src(ui_Image6, &ui_img_141844619);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -50);
    lv_obj_set_y(ui_Image6, 65);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image6, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ECG_screen_destroy(void)
{
    if(ui_ECG) lv_obj_del(ui_ECG);

    // NULL screen variables
    ui_ECG = NULL;
    ui_Button7 = NULL;
    ui_Label5 = NULL;
    ui_ComBarraStatus3 = NULL;
    ui_Chart2 = NULL;
    ui_Label22 = NULL;
    ui_LabelMedBPM2 = NULL;
    ui_Image6 = NULL;

}
