// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_GSR = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_ComBarraStatus4 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
// event funtions
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tela_Instrumento, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Instrumento_screen_init);
    }
}

// build funtions

void ui_GSR_screen_init(void)
{
    ui_GSR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button9 = lv_btn_create(ui_GSR);
    lv_obj_set_width(ui_Button9, 155);
    lv_obj_set_height(ui_Button9, 20);
    lv_obj_set_x(ui_Button9, -76);
    lv_obj_set_y(ui_Button9, -7);
    lv_obj_set_align(ui_Button9, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Voltar");

    ui_ComBarraStatus4 = ui_ComBarraStatus_create(ui_GSR);
    lv_obj_set_x(ui_ComBarraStatus4, 0);
    lv_obj_set_y(ui_ComBarraStatus4, 0);

    ui_Label27 = lv_label_create(ui_GSR);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "99");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xB800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_GSR);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, 40);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Normal");

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}

void ui_GSR_screen_destroy(void)
{
    if(ui_GSR) lv_obj_del(ui_GSR);

    // NULL screen variables
    ui_GSR = NULL;
    ui_Button9 = NULL;
    ui_Label16 = NULL;
    ui_ComBarraStatus4 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;

}
