// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_GSR_H
#define UI_GSR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GSR
extern void ui_GSR_screen_init(void);
extern void ui_GSR_screen_destroy(void);
extern lv_obj_t * ui_GSR;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_ComBarraStatus4;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

