// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_INSTRUMENTO_H
#define UI_INSTRUMENTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Instrumento
extern void ui_Instrumento_screen_init(void);
extern void ui_Instrumento_screen_destroy(void);
extern lv_obj_t * ui_Instrumento;
extern lv_obj_t * ui_Label5;
extern void ui_event_backButton1(lv_event_t * e);
extern lv_obj_t * ui_backButton1;
extern lv_obj_t * ui_Label11;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label8;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

