// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Instrumento = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_backButton1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_backButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Selecao_de_Modo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Selecao_de_Modo_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Termometro, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Termometro_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Oximetro, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Oximetro_screen_init);
    }
}

// build funtions

void ui_Instrumento_screen_init(void)
{
    ui_Instrumento = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Instrumento, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Instrumento, lv_color_hex(0x003F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Instrumento, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Instrumento);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -70);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SELECIONE INSTRUMENTO:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton1 = lv_btn_create(ui_Instrumento);
    lv_obj_set_width(ui_backButton1, 90);
    lv_obj_set_height(ui_backButton1, 35);
    lv_obj_set_x(ui_backButton1, -110);
    lv_obj_set_y(ui_backButton1, 95);
    lv_obj_set_align(ui_backButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton1, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_backButton1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Voltar");

    ui_Button2 = lv_btn_create(ui_Instrumento);
    lv_obj_set_width(ui_Button2, 110);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -26);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Termometro");

    ui_Button7 = lv_btn_create(ui_Instrumento);
    lv_obj_set_width(ui_Button7, 110);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, 36);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Oximetro");

    lv_obj_add_event_cb(ui_backButton1, ui_event_backButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}

void ui_Instrumento_screen_destroy(void)
{
    if(ui_Instrumento) lv_obj_del(ui_Instrumento);

    // NULL screen variables
    ui_Instrumento = NULL;
    ui_Label5 = NULL;
    ui_backButton1 = NULL;
    ui_Label11 = NULL;
    ui_Button2 = NULL;
    ui_Label8 = NULL;
    ui_Button7 = NULL;
    ui_Label16 = NULL;

}
