// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_MODO_REGISTRO_H
#define UI_MODO_REGISTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Modo_Registro
extern void ui_Modo_Registro_screen_init(void);
extern void ui_Modo_Registro_screen_destroy(void);
extern lv_obj_t * ui_Modo_Registro;
extern void ui_event_BTNovoRegistro(lv_event_t * e);
extern lv_obj_t * ui_BTNovoRegistro;
extern lv_obj_t * ui_Label6;
extern void ui_event_BTCarregarDados(lv_event_t * e);
extern lv_obj_t * ui_BTCarregarDados;
extern lv_obj_t * ui_Label7;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

