// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_LabelSalvar;
lv_obj_t * uic_BTSalvar;
lv_obj_t * ui_Novo_Registro = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_ComBarraStatus5 = NULL;
lv_obj_t * ui_BTSalvar = NULL;
lv_obj_t * ui_LabelSalvar = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
// event funtions
void ui_event_Novo_Registro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard4,  ui_TextArea2);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Modo_Registro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Modo_Registro_screen_init);
    }
}

void ui_event_BTSalvar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Dashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Dashboard_screen_init);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Novo_Registro_screen_init(void)
{
    ui_Novo_Registro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Novo_Registro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea2 = lv_textarea_create(ui_Novo_Registro);
    lv_obj_set_width(ui_TextArea2, 216);
    lv_obj_set_height(ui_TextArea2, 50);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, -45);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Nome do Paciente");

    ui_Label10 = lv_label_create(ui_Novo_Registro);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 10);
    lv_obj_set_y(ui_Label10, 8);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "dd/mm/aa hh::mm::ss");

    ui_Button5 = lv_btn_create(ui_Novo_Registro);
    lv_obj_set_width(ui_Button5, 155);
    lv_obj_set_height(ui_Button5, 20);
    lv_obj_set_x(ui_Button5, -76);
    lv_obj_set_y(ui_Button5, -7);
    lv_obj_set_align(ui_Button5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Voltar");

    ui_ComBarraStatus5 = ui_ComBarraStatus_create(ui_Novo_Registro);
    lv_obj_set_x(ui_ComBarraStatus5, 0);
    lv_obj_set_y(ui_ComBarraStatus5, 0);

    ui_BTSalvar = lv_btn_create(ui_Novo_Registro);
    lv_obj_set_width(ui_BTSalvar, 205);
    lv_obj_set_height(ui_BTSalvar, 43);
    lv_obj_set_x(ui_BTSalvar, 0);
    lv_obj_set_y(ui_BTSalvar, 50);
    lv_obj_set_align(ui_BTSalvar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTSalvar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTSalvar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTSalvar, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTSalvar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSalvar = lv_label_create(ui_BTSalvar);
    lv_obj_set_width(ui_LabelSalvar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalvar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSalvar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalvar, "INICIAR GRAVACAO");

    ui_Image1 = lv_img_create(ui_Novo_Registro);
    lv_img_set_src(ui_Image1, &ui_img_587847134);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -85);
    lv_obj_set_y(ui_Image1, 8);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard4 = lv_keyboard_create(ui_Novo_Registro);
    lv_obj_set_width(ui_Keyboard4, 320);
    lv_obj_set_height(ui_Keyboard4, 120);
    lv_obj_set_x(ui_Keyboard4, 0);
    lv_obj_set_y(ui_Keyboard4, 60);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_grad_dir(ui_Keyboard4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard4, 9, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTSalvar, ui_event_BTSalvar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Novo_Registro, ui_event_Novo_Registro, LV_EVENT_ALL, NULL);
    uic_BTSalvar = ui_BTSalvar;
    uic_LabelSalvar = ui_LabelSalvar;

}

void ui_Novo_Registro_screen_destroy(void)
{
    if(ui_Novo_Registro) lv_obj_del(ui_Novo_Registro);

    // NULL screen variables
    ui_Novo_Registro = NULL;
    ui_TextArea2 = NULL;
    ui_Label10 = NULL;
    ui_Button5 = NULL;
    ui_Label14 = NULL;
    ui_ComBarraStatus5 = NULL;
    uic_BTSalvar = NULL;
    ui_BTSalvar = NULL;
    uic_LabelSalvar = NULL;
    ui_LabelSalvar = NULL;
    ui_Image1 = NULL;
    ui_Keyboard4 = NULL;

}
