// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_NOVO_REGISTRO_H
#define UI_NOVO_REGISTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Novo_Registro
extern void ui_Novo_Registro_screen_init(void);
extern void ui_Novo_Registro_screen_destroy(void);
extern void ui_event_Novo_Registro(lv_event_t * e);
extern lv_obj_t * ui_Novo_Registro;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_ComBarraStatus5;
extern lv_obj_t * ui_BTSalvar;
extern lv_obj_t * ui_LabelSalvar;
extern lv_obj_t * ui_Image1;
extern void ui_event_Keyboard4(lv_event_t * e);
extern lv_obj_t * ui_Keyboard4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BTSalvar;
extern lv_obj_t * uic_LabelSalvar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

