// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_OXIMETRO_H
#define UI_OXIMETRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Oximetro
extern void ui_Oximetro_screen_init(void);
extern void ui_Oximetro_screen_destroy(void);
extern lv_obj_t * ui_Oximetro;
extern void ui_event_backButton9(lv_event_t * e);
extern lv_obj_t * ui_backButton9;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

