// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Oximetro = NULL;
lv_obj_t * ui_backButton9 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label17 = NULL;
// event funtions
void ui_event_backButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Selecao_de_Modo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Selecao_de_Modo_screen_init);
    }
}

// build funtions

void ui_Oximetro_screen_init(void)
{
    ui_Oximetro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Oximetro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Oximetro, lv_color_hex(0x003F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Oximetro, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton9 = lv_btn_create(ui_Oximetro);
    lv_obj_set_width(ui_backButton9, 90);
    lv_obj_set_height(ui_backButton9, 35);
    lv_obj_set_x(ui_backButton9, -110);
    lv_obj_set_y(ui_backButton9, 95);
    lv_obj_set_align(ui_backButton9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton9, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_backButton9);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Voltar");

    ui_Panel3 = lv_obj_create(ui_Oximetro);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "0");

    lv_obj_add_event_cb(ui_backButton9, ui_event_backButton9, LV_EVENT_ALL, NULL);

}

void ui_Oximetro_screen_destroy(void)
{
    if(ui_Oximetro) lv_obj_del(ui_Oximetro);

    // NULL screen variables
    ui_Oximetro = NULL;
    ui_backButton9 = NULL;
    ui_Label18 = NULL;
    ui_Panel3 = NULL;
    ui_Label17 = NULL;

}
