// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SELECAO_DE_MODO_H
#define UI_SELECAO_DE_MODO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Selecao_de_Modo
extern void ui_Selecao_de_Modo_screen_init(void);
extern void ui_Selecao_de_Modo_screen_destroy(void);
extern lv_obj_t * ui_Selecao_de_Modo;
extern void ui_event_BottomModoRegistro(lv_event_t * e);
extern lv_obj_t * ui_BottomModoRegistro;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image3;
extern void ui_event_BottomModoConsulta(lv_event_t * e);
extern lv_obj_t * ui_BottomModoConsulta;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_ComStatusBar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Selecao_de_Modo;
extern lv_obj_t * uic_BottomModoRegistro;
extern lv_obj_t * uic_Image3;
extern lv_obj_t * uic_BottomModoConsulta;
extern lv_obj_t * uic_Image2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

