// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_Image2;
lv_obj_t * uic_BottomModoConsulta;
lv_obj_t * uic_Image3;
lv_obj_t * uic_BottomModoRegistro;
lv_obj_t * uic_Selecao_de_Modo;
lv_obj_t * ui_Selecao_de_Modo = NULL;
lv_obj_t * ui_BottomModoRegistro = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_BottomModoConsulta = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_ComStatusBar = NULL;
// event funtions
void ui_event_BottomModoRegistro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Modo_Registro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Modo_Registro_screen_init);
    }
}

void ui_event_BottomModoConsulta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tela_Instrumento, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Instrumento_screen_init);
    }
}

// build funtions

void ui_Selecao_de_Modo_screen_init(void)
{
    ui_Selecao_de_Modo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Selecao_de_Modo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BottomModoRegistro = lv_btn_create(ui_Selecao_de_Modo);
    lv_obj_set_width(ui_BottomModoRegistro, 150);
    lv_obj_set_height(ui_BottomModoRegistro, 205);
    lv_obj_set_x(ui_BottomModoRegistro, 80);
    lv_obj_set_y(ui_BottomModoRegistro, 10);
    lv_obj_set_align(ui_BottomModoRegistro, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomModoRegistro, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BottomModoRegistro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomModoRegistro, lv_color_hex(0x303A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomModoRegistro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BottomModoRegistro);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 25);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Registro");

    ui_Image3 = lv_img_create(ui_BottomModoRegistro);
    lv_img_set_src(ui_Image3, &ui_img_586855341);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -25);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BottomModoConsulta = lv_btn_create(ui_Selecao_de_Modo);
    lv_obj_set_width(ui_BottomModoConsulta, 150);
    lv_obj_set_height(ui_BottomModoConsulta, 205);
    lv_obj_set_x(ui_BottomModoConsulta, -80);
    lv_obj_set_y(ui_BottomModoConsulta, 10);
    lv_obj_set_align(ui_BottomModoConsulta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomModoConsulta, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BottomModoConsulta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomModoConsulta, lv_color_hex(0x5FBBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomModoConsulta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_BottomModoConsulta);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 25);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Consulta");

    ui_Image2 = lv_img_create(ui_BottomModoConsulta);
    lv_img_set_src(ui_Image2, &ui_img_939456327);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -25);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ComStatusBar = ui_ComBarraStatus_create(ui_Selecao_de_Modo);
    lv_obj_set_x(ui_ComStatusBar, 0);
    lv_obj_set_y(ui_ComStatusBar, 0);

    lv_obj_add_event_cb(ui_BottomModoRegistro, ui_event_BottomModoRegistro, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomModoConsulta, ui_event_BottomModoConsulta, LV_EVENT_ALL, NULL);
    uic_Selecao_de_Modo = ui_Selecao_de_Modo;
    uic_BottomModoRegistro = ui_BottomModoRegistro;
    uic_Image3 = ui_Image3;
    uic_BottomModoConsulta = ui_BottomModoConsulta;
    uic_Image2 = ui_Image2;

}

void ui_Selecao_de_Modo_screen_destroy(void)
{
    if(ui_Selecao_de_Modo) lv_obj_del(ui_Selecao_de_Modo);

    // NULL screen variables
    uic_Selecao_de_Modo = NULL;
    ui_Selecao_de_Modo = NULL;
    uic_BottomModoRegistro = NULL;
    ui_BottomModoRegistro = NULL;
    ui_Label4 = NULL;
    uic_Image3 = NULL;
    ui_Image3 = NULL;
    uic_BottomModoConsulta = NULL;
    ui_BottomModoConsulta = NULL;
    ui_Label3 = NULL;
    uic_Image2 = NULL;
    ui_Image2 = NULL;
    ui_ComStatusBar = NULL;

}
