// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_TELA_OXIMETRO_H
#define UI_TELA_OXIMETRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Oximetro
extern void ui_Tela_Oximetro_screen_init(void);
extern void ui_Tela_Oximetro_screen_destroy(void);
extern lv_obj_t * ui_Tela_Oximetro;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_ComBarraStatus2;
extern lv_obj_t * ui_ContMedOximetro;
extern lv_obj_t * ui_LabelMedSpO2;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_LabelMedBPM;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_ChartPPG;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ContMedOximetro;
extern lv_obj_t * uic_LabelMedSpO2;
extern lv_obj_t * uic_LabelMedTermometro;
extern lv_obj_t * uic_ChartPPG;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

