// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_Termometro;
lv_obj_t * ui_Tela_Termometro = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ComBarraStatus1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions

// build funtions

void ui_Tela_Termometro_screen_init(void)
{
    ui_Tela_Termometro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_Termometro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_Tela_Termometro);
    lv_obj_set_width(ui_Button6, 155);
    lv_obj_set_height(ui_Button6, 20);
    lv_obj_set_x(ui_Button6, -76);
    lv_obj_set_y(ui_Button6, -7);
    lv_obj_set_align(ui_Button6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Voltar");

    ui_ComBarraStatus1 = ui_ComBarraStatus_create(ui_Tela_Termometro);
    lv_obj_set_x(ui_ComBarraStatus1, 0);
    lv_obj_set_y(ui_ComBarraStatus1, 0);

    ui_Arc1 = lv_arc_create(ui_Tela_Termometro);
    lv_obj_set_width(ui_Arc1, 115);
    lv_obj_set_height(ui_Arc1, 115);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 340, 420);
    lv_arc_set_value(ui_Arc1, 365);
    lv_arc_set_bg_angles(ui_Arc1, 135, 45);
    lv_obj_set_style_bg_img_src(ui_Arc1, &ui_img_177543304, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Arc1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x00E676), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0x00E676), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 24, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_177543304, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label21, "Normal");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Arc1);
    lv_img_set_src(ui_Image5, &ui_img_96564182);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Image5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x171F27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Image5);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "99");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Image5);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -2);
    lv_obj_set_align(ui_Label20, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label20, "°C");

    uic_Termometro = ui_Tela_Termometro;

}

void ui_Tela_Termometro_screen_destroy(void)
{
    if(ui_Tela_Termometro) lv_obj_del(ui_Tela_Termometro);

    // NULL screen variables
    uic_Termometro = NULL;
    ui_Tela_Termometro = NULL;
    ui_Button6 = NULL;
    ui_Label2 = NULL;
    ui_ComBarraStatus1 = NULL;
    ui_Arc1 = NULL;
    ui_Label21 = NULL;
    ui_Image5 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;

}
