// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_TELA_TERMOMETRO_H
#define UI_TELA_TERMOMETRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Termometro
extern void ui_Tela_Termometro_screen_init(void);
extern void ui_Tela_Termometro_screen_destroy(void);
extern lv_obj_t * ui_Tela_Termometro;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ComBarraStatus1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Termometro;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

