// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_TERMOMETRO_H
#define UI_TERMOMETRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Termometro
extern void ui_Termometro_screen_init(void);
extern void ui_Termometro_screen_destroy(void);
extern lv_obj_t * ui_Termometro;
extern void ui_event_backButton6(lv_event_t * e);
extern lv_obj_t * ui_backButton6;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

