// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Termometro = NULL;
lv_obj_t * ui_backButton6 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_backButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Instrumento, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Instrumento_screen_init);
    }
}

// build funtions

void ui_Termometro_screen_init(void)
{
    ui_Termometro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Termometro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Termometro, lv_color_hex(0x003F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Termometro, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButton6 = lv_btn_create(ui_Termometro);
    lv_obj_set_width(ui_backButton6, 90);
    lv_obj_set_height(ui_backButton6, 35);
    lv_obj_set_x(ui_backButton6, -110);
    lv_obj_set_y(ui_backButton6, 95);
    lv_obj_set_align(ui_backButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton6, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_backButton6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Voltar");

    ui_Panel2 = lv_obj_create(ui_Termometro);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "0");

    lv_obj_add_event_cb(ui_backButton6, ui_event_backButton6, LV_EVENT_ALL, NULL);

}

void ui_Termometro_screen_destroy(void)
{
    if(ui_Termometro) lv_obj_del(ui_Termometro);

    // NULL screen variables
    ui_Termometro = NULL;
    ui_backButton6 = NULL;
    ui_Label12 = NULL;
    ui_Panel2 = NULL;
    ui_Label20 = NULL;

}
