// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_ChartPPG;
lv_obj_t * uic_LabelMedTermometro;
lv_obj_t * uic_LabelMedSpO2;
lv_obj_t * uic_ContMedOximetro;
lv_obj_t * ui_Tela_Oximetro = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_ComBarraStatus2 = NULL;
lv_obj_t * ui_ContMedOximetro = NULL;
lv_obj_t * ui_LabelMedSpO2 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_LabelMedBPM = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_ChartPPG = NULL;
// event funtions

// build funtions

void ui_Tela_Oximetro_screen_init(void)
{
    ui_Tela_Oximetro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_Oximetro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_Tela_Oximetro);
    lv_obj_set_width(ui_Button8, 155);
    lv_obj_set_height(ui_Button8, 20);
    lv_obj_set_x(ui_Button8, -76);
    lv_obj_set_y(ui_Button8, -7);
    lv_obj_set_align(ui_Button8, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Voltar");

    ui_ComBarraStatus2 = ui_ComBarraStatus_create(ui_Tela_Oximetro);
    lv_obj_set_x(ui_ComBarraStatus2, 0);
    lv_obj_set_y(ui_ComBarraStatus2, 0);

    ui_ContMedOximetro = lv_obj_create(ui_Tela_Oximetro);
    lv_obj_remove_style_all(ui_ContMedOximetro);
    lv_obj_set_width(ui_ContMedOximetro, 140);
    lv_obj_set_height(ui_ContMedOximetro, 170);
    lv_obj_set_x(ui_ContMedOximetro, 20);
    lv_obj_set_y(ui_ContMedOximetro, 0);
    lv_obj_set_align(ui_ContMedOximetro, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ContMedOximetro, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMedSpO2 = lv_label_create(ui_ContMedOximetro);
    lv_obj_set_width(ui_LabelMedSpO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMedSpO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMedSpO2, 0);
    lv_obj_set_y(ui_LabelMedSpO2, -50);
    lv_obj_set_align(ui_LabelMedSpO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMedSpO2, "99");
    lv_obj_set_style_text_color(ui_LabelMedSpO2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMedSpO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMedSpO2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_ContMedOximetro);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -15);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "SpO2");

    ui_LabelMedBPM = lv_label_create(ui_ContMedOximetro);
    lv_obj_set_width(ui_LabelMedBPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMedBPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMedBPM, 0);
    lv_obj_set_y(ui_LabelMedBPM, 35);
    lv_obj_set_align(ui_LabelMedBPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMedBPM, "99");
    lv_obj_set_style_text_color(ui_LabelMedBPM, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMedBPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMedBPM, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_ContMedOximetro);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 70);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "BPM");

    ui_Image4 = lv_img_create(ui_ContMedOximetro);
    lv_img_set_src(ui_Image4, &ui_img_141844619);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -33);
    lv_obj_set_y(ui_Image4, 70);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartPPG = lv_chart_create(ui_Tela_Oximetro);
    lv_obj_set_width(ui_ChartPPG, 110);
    lv_obj_set_height(ui_ChartPPG, 180);
    lv_obj_set_x(ui_ChartPPG, -40);
    lv_obj_set_y(ui_ChartPPG, 0);
    lv_obj_set_align(ui_ChartPPG, LV_ALIGN_RIGHT_MID);
    lv_chart_set_type(ui_ChartPPG, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartPPG, 50);
    lv_chart_set_range(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_Y, -500, 500);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_ChartPPG_series_1 = lv_chart_add_series(ui_ChartPPG, lv_color_hex(0x00FF36),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartPPG_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartPPG, ui_ChartPPG_series_1, ui_ChartPPG_series_1_array);
    lv_obj_set_style_bg_color(ui_ChartPPG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartPPG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartPPG, lv_color_hex(0x4040FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartPPG, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChartPPG, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartPPG, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartPPG, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartPPG, 0, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ChartPPG, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartPPG, 0, LV_PART_TICKS | LV_STATE_DEFAULT);

    uic_ContMedOximetro = ui_ContMedOximetro;
    uic_LabelMedSpO2 = ui_LabelMedSpO2;
    uic_LabelMedTermometro = ui_LabelMedBPM;
    uic_ChartPPG = ui_ChartPPG;

}

void ui_Tela_Oximetro_screen_destroy(void)
{
    if(ui_Tela_Oximetro) lv_obj_del(ui_Tela_Oximetro);

    // NULL screen variables
    ui_Tela_Oximetro = NULL;
    ui_Button8 = NULL;
    ui_Label12 = NULL;
    ui_ComBarraStatus2 = NULL;
    uic_ContMedOximetro = NULL;
    ui_ContMedOximetro = NULL;
    uic_LabelMedSpO2 = NULL;
    ui_LabelMedSpO2 = NULL;
    ui_Label17 = NULL;
    uic_LabelMedTermometro = NULL;
    ui_LabelMedBPM = NULL;
    ui_Label18 = NULL;
    ui_Image4 = NULL;
    uic_ChartPPG = NULL;
    ui_ChartPPG = NULL;

}
