// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_TELA_INSTRUMENTO_H
#define UI_TELA_INSTRUMENTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Instrumento
extern void ui_Tela_Instrumento_screen_init(void);
extern void ui_Tela_Instrumento_screen_destroy(void);
extern lv_obj_t * ui_Tela_Instrumento;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Lista_de_Sensores;
extern void ui_event_ContTermometro(lv_event_t * e);
extern lv_obj_t * ui_ContTermometro;
extern lv_obj_t * ui_Barra_Cor5;
extern lv_obj_t * ui_Lbl_Titulo5;
extern lv_obj_t * ui_Img_Icone5;
extern lv_obj_t * ui_Img_Seta5;
extern void ui_event_ContOximetro(lv_event_t * e);
extern lv_obj_t * ui_ContOximetro;
extern lv_obj_t * ui_Barra_Cor1;
extern lv_obj_t * ui_Lbl_Titulo1;
extern lv_obj_t * ui_Img_Icone1;
extern lv_obj_t * ui_Img_Seta1;
extern void ui_event_ContECG(lv_event_t * e);
extern lv_obj_t * ui_ContECG;
extern lv_obj_t * ui_Barra_Cor2;
extern lv_obj_t * ui_Lbl_ECG;
extern lv_obj_t * ui_Img_Icone2;
extern lv_obj_t * ui_Img_Seta2;
extern void ui_event_ContGSR(lv_event_t * e);
extern lv_obj_t * ui_ContGSR;
extern lv_obj_t * ui_Barra_Cor4;
extern lv_obj_t * ui_Lbl_Titulo4;
extern lv_obj_t * ui_Img_Icone4;
extern lv_obj_t * ui_Img_Seta4;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_ComStatusBar2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Instrumento;
extern lv_obj_t * uic_Lista_de_Sensores;
extern lv_obj_t * uic_ContOximetro;
extern lv_obj_t * uic_ContGSR;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

