// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * uic_ContGSR;
lv_obj_t * uic_ContOximetro;
lv_obj_t * uic_Lista_de_Sensores;
lv_obj_t * uic_Instrumento;
lv_obj_t * ui_Tela_Instrumento = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Lista_de_Sensores = NULL;
lv_obj_t * ui_ContTermometro = NULL;
lv_obj_t * ui_Barra_Cor5 = NULL;
lv_obj_t * ui_Lbl_Titulo5 = NULL;
lv_obj_t * ui_Img_Icone5 = NULL;
lv_obj_t * ui_Img_Seta5 = NULL;
lv_obj_t * ui_ContOximetro = NULL;
lv_obj_t * ui_Barra_Cor1 = NULL;
lv_obj_t * ui_Lbl_Titulo1 = NULL;
lv_obj_t * ui_Img_Icone1 = NULL;
lv_obj_t * ui_Img_Seta1 = NULL;
lv_obj_t * ui_ContECG = NULL;
lv_obj_t * ui_Barra_Cor2 = NULL;
lv_obj_t * ui_Lbl_ECG = NULL;
lv_obj_t * ui_Img_Icone2 = NULL;
lv_obj_t * ui_Img_Seta2 = NULL;
lv_obj_t * ui_ContGSR = NULL;
lv_obj_t * ui_Barra_Cor4 = NULL;
lv_obj_t * ui_Lbl_Titulo4 = NULL;
lv_obj_t * ui_Img_Icone4 = NULL;
lv_obj_t * ui_Img_Seta4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_ComStatusBar2 = NULL;
// event funtions
void ui_event_ContTermometro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Tela_Termometro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Termometro_screen_init);
    }
}

void ui_event_ContOximetro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Tela_Oximetro, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Tela_Oximetro_screen_init);
    }
}

void ui_event_ContECG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_ECG, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ECG_screen_init);
    }
}

void ui_event_ContGSR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_GSR, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_GSR_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Selecao_de_Modo, LV_SCR_LOAD_ANIM_FADE_ON, 400, 0, &ui_Selecao_de_Modo_screen_init);
    }
}

// build funtions

void ui_Tela_Instrumento_screen_init(void)
{
    ui_Tela_Instrumento = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_Instrumento, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Tela_Instrumento);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 35);
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "Instrumento");

    ui_Lista_de_Sensores = lv_obj_create(ui_Tela_Instrumento);
    lv_obj_set_width(ui_Lista_de_Sensores, 280);
    lv_obj_set_height(ui_Lista_de_Sensores, 160);
    lv_obj_set_align(ui_Lista_de_Sensores, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Lista_de_Sensores, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Lista_de_Sensores, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Lista_de_Sensores, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lista_de_Sensores, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Lista_de_Sensores, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContTermometro = lv_obj_create(ui_Lista_de_Sensores);
    lv_obj_remove_style_all(ui_ContTermometro);
    lv_obj_set_width(ui_ContTermometro, 280);
    lv_obj_set_height(ui_ContTermometro, 50);
    lv_obj_set_align(ui_ContTermometro, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContTermometro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContTermometro, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContTermometro, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContTermometro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Barra_Cor5 = lv_obj_create(ui_ContTermometro);
    lv_obj_set_width(ui_Barra_Cor5, 10);
    lv_obj_set_height(ui_Barra_Cor5, lv_pct(142));
    lv_obj_set_align(ui_Barra_Cor5, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Barra_Cor5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Barra_Cor5, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Barra_Cor5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Barra_Cor5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lbl_Titulo5 = lv_label_create(ui_ContTermometro);
    lv_obj_set_width(ui_Lbl_Titulo5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lbl_Titulo5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lbl_Titulo5, 70);
    lv_obj_set_y(ui_Lbl_Titulo5, 0);
    lv_obj_set_align(ui_Lbl_Titulo5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lbl_Titulo5, "Termometro");

    ui_Img_Icone5 = lv_img_create(ui_ContTermometro);
    lv_img_set_src(ui_Img_Icone5, &ui_img_1635948304);
    lv_obj_set_width(ui_Img_Icone5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Icone5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Icone5, 20);
    lv_obj_set_y(ui_Img_Icone5, 0);
    lv_obj_set_align(ui_Img_Icone5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Img_Icone5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Icone5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Img_Icone5, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Img_Icone5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img_Seta5 = lv_img_create(ui_ContTermometro);
    lv_img_set_src(ui_Img_Seta5, &ui_img_652512494);
    lv_obj_set_width(ui_Img_Seta5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Seta5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Seta5, -10);
    lv_obj_set_y(ui_Img_Seta5, 0);
    lv_obj_set_align(ui_Img_Seta5, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Img_Seta5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Seta5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContOximetro = lv_obj_create(ui_Lista_de_Sensores);
    lv_obj_remove_style_all(ui_ContOximetro);
    lv_obj_set_width(ui_ContOximetro, 280);
    lv_obj_set_height(ui_ContOximetro, 50);
    lv_obj_set_align(ui_ContOximetro, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContOximetro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContOximetro, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContOximetro, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContOximetro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Barra_Cor1 = lv_obj_create(ui_ContOximetro);
    lv_obj_set_width(ui_Barra_Cor1, 10);
    lv_obj_set_height(ui_Barra_Cor1, lv_pct(142));
    lv_obj_set_align(ui_Barra_Cor1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Barra_Cor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Barra_Cor1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Barra_Cor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Barra_Cor1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lbl_Titulo1 = lv_label_create(ui_ContOximetro);
    lv_obj_set_width(ui_Lbl_Titulo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lbl_Titulo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lbl_Titulo1, 70);
    lv_obj_set_y(ui_Lbl_Titulo1, 0);
    lv_obj_set_align(ui_Lbl_Titulo1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lbl_Titulo1, "Oximetro");

    ui_Img_Icone1 = lv_img_create(ui_ContOximetro);
    lv_img_set_src(ui_Img_Icone1, &ui_img_1680349653);
    lv_obj_set_width(ui_Img_Icone1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Icone1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Icone1, 20);
    lv_obj_set_y(ui_Img_Icone1, 0);
    lv_obj_set_align(ui_Img_Icone1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Img_Icone1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Icone1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Img_Icone1, 200);
    lv_obj_set_style_img_recolor(ui_Img_Icone1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Img_Icone1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img_Seta1 = lv_img_create(ui_ContOximetro);
    lv_img_set_src(ui_Img_Seta1, &ui_img_652512494);
    lv_obj_set_width(ui_Img_Seta1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Seta1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Seta1, -10);
    lv_obj_set_y(ui_Img_Seta1, 0);
    lv_obj_set_align(ui_Img_Seta1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Img_Seta1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Seta1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContECG = lv_obj_create(ui_Lista_de_Sensores);
    lv_obj_remove_style_all(ui_ContECG);
    lv_obj_set_width(ui_ContECG, 280);
    lv_obj_set_height(ui_ContECG, 50);
    lv_obj_set_x(ui_ContECG, 0);
    lv_obj_set_y(ui_ContECG, -1);
    lv_obj_set_align(ui_ContECG, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContECG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContECG, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContECG, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContECG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Barra_Cor2 = lv_obj_create(ui_ContECG);
    lv_obj_set_width(ui_Barra_Cor2, 10);
    lv_obj_set_height(ui_Barra_Cor2, lv_pct(142));
    lv_obj_set_align(ui_Barra_Cor2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Barra_Cor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Barra_Cor2, lv_color_hex(0x1FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Barra_Cor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Barra_Cor2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lbl_ECG = lv_label_create(ui_ContECG);
    lv_obj_set_width(ui_Lbl_ECG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lbl_ECG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lbl_ECG, 70);
    lv_obj_set_y(ui_Lbl_ECG, 0);
    lv_obj_set_align(ui_Lbl_ECG, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lbl_ECG, "Eletrocardiograma (ECG)");

    ui_Img_Icone2 = lv_img_create(ui_ContECG);
    lv_img_set_src(ui_Img_Icone2, &ui_img_134478313);
    lv_obj_set_width(ui_Img_Icone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Icone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Icone2, 20);
    lv_obj_set_y(ui_Img_Icone2, 0);
    lv_obj_set_align(ui_Img_Icone2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Img_Icone2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Icone2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Img_Icone2, 270);
    lv_obj_set_style_img_recolor(ui_Img_Icone2, lv_color_hex(0x1FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Img_Icone2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img_Seta2 = lv_img_create(ui_ContECG);
    lv_img_set_src(ui_Img_Seta2, &ui_img_652512494);
    lv_obj_set_width(ui_Img_Seta2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Seta2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Seta2, -10);
    lv_obj_set_y(ui_Img_Seta2, 0);
    lv_obj_set_align(ui_Img_Seta2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Img_Seta2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Seta2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContGSR = lv_obj_create(ui_Lista_de_Sensores);
    lv_obj_remove_style_all(ui_ContGSR);
    lv_obj_set_width(ui_ContGSR, 280);
    lv_obj_set_height(ui_ContGSR, 50);
    lv_obj_set_align(ui_ContGSR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContGSR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContGSR, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContGSR, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContGSR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Barra_Cor4 = lv_obj_create(ui_ContGSR);
    lv_obj_set_width(ui_Barra_Cor4, 10);
    lv_obj_set_height(ui_Barra_Cor4, lv_pct(142));
    lv_obj_set_align(ui_Barra_Cor4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Barra_Cor4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Barra_Cor4, lv_color_hex(0xB800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Barra_Cor4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Barra_Cor4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lbl_Titulo4 = lv_label_create(ui_ContGSR);
    lv_obj_set_width(ui_Lbl_Titulo4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lbl_Titulo4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lbl_Titulo4, 70);
    lv_obj_set_y(ui_Lbl_Titulo4, 0);
    lv_obj_set_align(ui_Lbl_Titulo4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lbl_Titulo4, "Nivel de Estresse (GSR)");

    ui_Img_Icone4 = lv_img_create(ui_ContGSR);
    lv_img_set_src(ui_Img_Icone4, &ui_img_134478313);
    lv_obj_set_width(ui_Img_Icone4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Icone4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Icone4, 20);
    lv_obj_set_y(ui_Img_Icone4, 0);
    lv_obj_set_align(ui_Img_Icone4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Img_Icone4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Icone4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Img_Icone4, lv_color_hex(0xB800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Img_Icone4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img_Seta4 = lv_img_create(ui_ContGSR);
    lv_img_set_src(ui_Img_Seta4, &ui_img_652512494);
    lv_obj_set_width(ui_Img_Seta4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img_Seta4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img_Seta4, -10);
    lv_obj_set_y(ui_Img_Seta4, 0);
    lv_obj_set_align(ui_Img_Seta4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Img_Seta4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img_Seta4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Tela_Instrumento);
    lv_obj_set_width(ui_Button1, 155);
    lv_obj_set_height(ui_Button1, 20);
    lv_obj_set_x(ui_Button1, -76);
    lv_obj_set_y(ui_Button1, -7);
    lv_obj_set_align(ui_Button1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Voltar");

    ui_ComStatusBar2 = ui_ComBarraStatus_create(ui_Tela_Instrumento);
    lv_obj_set_x(ui_ComStatusBar2, 0);
    lv_obj_set_y(ui_ComStatusBar2, 0);

    lv_obj_add_event_cb(ui_ContTermometro, ui_event_ContTermometro, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContOximetro, ui_event_ContOximetro, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContECG, ui_event_ContECG, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContGSR, ui_event_ContGSR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    uic_Instrumento = ui_Tela_Instrumento;
    uic_Lista_de_Sensores = ui_Lista_de_Sensores;
    uic_ContOximetro = ui_ContOximetro;
    uic_ContGSR = ui_ContGSR;

}

void ui_Tela_Instrumento_screen_destroy(void)
{
    if(ui_Tela_Instrumento) lv_obj_del(ui_Tela_Instrumento);

    // NULL screen variables
    uic_Instrumento = NULL;
    ui_Tela_Instrumento = NULL;
    ui_Label8 = NULL;
    uic_Lista_de_Sensores = NULL;
    ui_Lista_de_Sensores = NULL;
    ui_ContTermometro = NULL;
    ui_Barra_Cor5 = NULL;
    ui_Lbl_Titulo5 = NULL;
    ui_Img_Icone5 = NULL;
    ui_Img_Seta5 = NULL;
    uic_ContOximetro = NULL;
    ui_ContOximetro = NULL;
    ui_Barra_Cor1 = NULL;
    ui_Lbl_Titulo1 = NULL;
    ui_Img_Icone1 = NULL;
    ui_Img_Seta1 = NULL;
    ui_ContECG = NULL;
    ui_Barra_Cor2 = NULL;
    ui_Lbl_ECG = NULL;
    ui_Img_Icone2 = NULL;
    ui_Img_Seta2 = NULL;
    uic_ContGSR = NULL;
    ui_ContGSR = NULL;
    ui_Barra_Cor4 = NULL;
    ui_Lbl_Titulo4 = NULL;
    ui_Img_Icone4 = NULL;
    ui_Img_Seta4 = NULL;
    ui_Button1 = NULL;
    ui_Label11 = NULL;
    ui_ComStatusBar2 = NULL;

}
