// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Tela_Inicial.h"
#include "ui_Selecao_de_Modo.h"
#include "ui_Modo_Consulta.h"
#include "ui_Modo_Registro.h"
#include "ui_Novo_Registro.h"
#include "ui_Carregar_Dados.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Blink_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mbi_logo_png);    // assets/MBI_logo.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
