// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_CARREGAR_DADOS_H
#define UI_CARREGAR_DADOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Carregar_Dados
extern void ui_Carregar_Dados_screen_init(void);
extern void ui_Carregar_Dados_screen_destroy(void);
extern lv_obj_t * ui_Carregar_Dados;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

