// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Modo_Consulta = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Modo_Consulta_screen_init(void)
{
    ui_Modo_Consulta = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Modo_Consulta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Modo_Consulta);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 7);
    lv_obj_set_y(ui_Label5, 31);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Selecionar Instrumento:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Modo_Consulta);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -9);
    lv_obj_set_y(ui_Label8, -8);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "(. . .)");

}

void ui_Modo_Consulta_screen_destroy(void)
{
    if(ui_Modo_Consulta) lv_obj_del(ui_Modo_Consulta);

    // NULL screen variables
    ui_Modo_Consulta = NULL;
    ui_Label5 = NULL;
    ui_Label8 = NULL;

}
