// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui_mbi

#include "ui.h"

lv_obj_t * ui_Modo_Consulta = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Modo_Consulta_screen_init(void)
{
    ui_Modo_Consulta = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Modo_Consulta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Modo_Consulta);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, ". . .");

}

void ui_Modo_Consulta_screen_destroy(void)
{
    if(ui_Modo_Consulta) lv_obj_del(ui_Modo_Consulta);

    // NULL screen variables
    ui_Modo_Consulta = NULL;
    ui_Label5 = NULL;

}
