// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Modo_Registro = NULL;
lv_obj_t * ui_BTNovoRegistro = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_BTCarregarDados = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_BTNovoRegistro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Novo_Usuario, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Novo_Usuario_screen_init);
    }
}

// build funtions

void ui_Modo_Registro_screen_init(void)
{
    ui_Modo_Registro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Modo_Registro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTNovoRegistro = lv_btn_create(ui_Modo_Registro);
    lv_obj_set_width(ui_BTNovoRegistro, 123);
    lv_obj_set_height(ui_BTNovoRegistro, 50);
    lv_obj_set_x(ui_BTNovoRegistro, -7);
    lv_obj_set_y(ui_BTNovoRegistro, -45);
    lv_obj_set_align(ui_BTNovoRegistro, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNovoRegistro, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNovoRegistro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_BTNovoRegistro);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 1);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Novo Registro");

    ui_BTCarregarDados = lv_btn_create(ui_Modo_Registro);
    lv_obj_set_width(ui_BTCarregarDados, 125);
    lv_obj_set_height(ui_BTCarregarDados, 50);
    lv_obj_set_x(ui_BTCarregarDados, -9);
    lv_obj_set_y(ui_BTCarregarDados, 36);
    lv_obj_set_align(ui_BTCarregarDados, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTCarregarDados, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTCarregarDados, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_BTCarregarDados);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 2);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Carregar Dados");

    lv_obj_add_event_cb(ui_BTNovoRegistro, ui_event_BTNovoRegistro, LV_EVENT_ALL, NULL);

}

void ui_Modo_Registro_screen_destroy(void)
{
    if(ui_Modo_Registro) lv_obj_del(ui_Modo_Registro);

    // NULL screen variables
    ui_Modo_Registro = NULL;
    ui_BTNovoRegistro = NULL;
    ui_Label6 = NULL;
    ui_BTCarregarDados = NULL;
    ui_Label7 = NULL;

}
