// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui_mbi

#ifndef UI_MODO_REGISTRO_H
#define UI_MODO_REGISTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Modo_Registro
extern void ui_Modo_Registro_screen_init(void);
extern void ui_Modo_Registro_screen_destroy(void);
extern lv_obj_t * ui_Modo_Registro;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

