// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Novo_Usuario = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
// event funtions
void ui_event_Novo_Usuario(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard4,  ui_TextArea2);
    }
}

// build funtions

void ui_Novo_Usuario_screen_init(void)
{
    ui_Novo_Usuario = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Novo_Usuario, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard4 = lv_keyboard_create(ui_Novo_Usuario);
    lv_obj_set_width(ui_Keyboard4, 300);
    lv_obj_set_height(ui_Keyboard4, 120);
    lv_obj_set_x(ui_Keyboard4, 2);
    lv_obj_set_y(ui_Keyboard4, 50);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextArea2 = lv_textarea_create(ui_Novo_Usuario);
    lv_obj_set_width(ui_TextArea2, 150);
    lv_obj_set_height(ui_TextArea2, 42);
    lv_obj_set_x(ui_TextArea2, -71);
    lv_obj_set_y(ui_TextArea2, -57);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Digite nome");

    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Novo_Usuario, ui_event_Novo_Usuario, LV_EVENT_ALL, NULL);

}

void ui_Novo_Usuario_screen_destroy(void)
{
    if(ui_Novo_Usuario) lv_obj_del(ui_Novo_Usuario);

    // NULL screen variables
    ui_Novo_Usuario = NULL;
    ui_Keyboard4 = NULL;
    ui_TextArea2 = NULL;

}
