// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_NOVO_USUARIO_H
#define UI_NOVO_USUARIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Novo_Usuario
extern void ui_Novo_Usuario_screen_init(void);
extern void ui_Novo_Usuario_screen_destroy(void);
extern void ui_event_Novo_Usuario(lv_event_t * e);
extern lv_obj_t * ui_Novo_Usuario;
extern lv_obj_t * ui_Keyboard4;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

