// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_SELECAO_DE_MODO_H
#define UI_SELECAO_DE_MODO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Selecao_de_Modo
extern void ui_Selecao_de_Modo_screen_init(void);
extern void ui_Selecao_de_Modo_screen_destroy(void);
extern void ui_event_Selecao_de_Modo(lv_event_t * e);
extern lv_obj_t * ui_Selecao_de_Modo;
extern lv_obj_t * ui_BTModoConsulta;
extern lv_obj_t * ui_Label3;
extern void ui_event_BTModoRegistro(lv_event_t * e);
extern lv_obj_t * ui_BTModoRegistro;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

