// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Selecao_de_Modo = NULL;
lv_obj_t * ui_BTModoConsulta = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_BTModoRegistro = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_Selecao_de_Modo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Modo_Consulta, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Modo_Consulta_screen_init);
    }
}

void ui_event_BTModoRegistro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Modo_Registro, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Modo_Registro_screen_init);
    }
}

// build funtions

void ui_Selecao_de_Modo_screen_init(void)
{
    ui_Selecao_de_Modo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Selecao_de_Modo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTModoConsulta = lv_btn_create(ui_Selecao_de_Modo);
    lv_obj_set_width(ui_BTModoConsulta, 126);
    lv_obj_set_height(ui_BTModoConsulta, 50);
    lv_obj_set_x(ui_BTModoConsulta, -73);
    lv_obj_set_y(ui_BTModoConsulta, -3);
    lv_obj_set_align(ui_BTModoConsulta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTModoConsulta, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTModoConsulta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_BTModoConsulta);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Modo Consulta");

    ui_BTModoRegistro = lv_btn_create(ui_Selecao_de_Modo);
    lv_obj_set_width(ui_BTModoRegistro, 131);
    lv_obj_set_height(ui_BTModoRegistro, 50);
    lv_obj_set_x(ui_BTModoRegistro, 66);
    lv_obj_set_y(ui_BTModoRegistro, -2);
    lv_obj_set_align(ui_BTModoRegistro, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTModoRegistro, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTModoRegistro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BTModoRegistro);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Modo Registro");

    ui_Label2 = lv_label_create(ui_Selecao_de_Modo);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -10);
    lv_obj_set_y(ui_Label2, -64);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Selecionar Modo:");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTModoRegistro, ui_event_BTModoRegistro, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Selecao_de_Modo, ui_event_Selecao_de_Modo, LV_EVENT_ALL, NULL);

}

void ui_Selecao_de_Modo_screen_destroy(void)
{
    if(ui_Selecao_de_Modo) lv_obj_del(ui_Selecao_de_Modo);

    // NULL screen variables
    ui_Selecao_de_Modo = NULL;
    ui_BTModoConsulta = NULL;
    ui_Label3 = NULL;
    ui_BTModoRegistro = NULL;
    ui_Label4 = NULL;
    ui_Label2 = NULL;

}
