// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Tela_Inicial = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_Tela_Inicial(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Selecao_de_Modo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Selecao_de_Modo_screen_init);
    }
}

// build funtions

void ui_Tela_Inicial_screen_init(void)
{
    ui_Tela_Inicial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_Inicial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tela_Inicial, lv_color_hex(0x0079FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tela_Inicial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Tela_Inicial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Tela_Inicial, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Tela_Inicial, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Tela_Inicial);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "MBI\nModulo Biometrico Integrado");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Tela_Inicial, ui_event_Tela_Inicial, LV_EVENT_ALL, NULL);

}

void ui_Tela_Inicial_screen_destroy(void)
{
    if(ui_Tela_Inicial) lv_obj_del(ui_Tela_Inicial);

    // NULL screen variables
    ui_Tela_Inicial = NULL;
    ui_Label9 = NULL;

}
