// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui_mbi

#include "ui.h"

lv_obj_t * ui_Tela_Inicial = NULL;
lv_obj_t * ui_Titulo = NULL;
// event funtions
void ui_event_Tela_Inicial(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tela_de_Modo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Tela_de_Modo_screen_init);
    }
}

// build funtions

void ui_Tela_Inicial_screen_init(void)
{
    ui_Tela_Inicial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_Inicial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Titulo = lv_label_create(ui_Tela_Inicial);
    lv_obj_set_width(ui_Titulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Titulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Titulo, 2);
    lv_obj_set_y(ui_Titulo, -4);
    lv_obj_set_align(ui_Titulo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Titulo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Titulo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Titulo, "												MBI\n(Modulo BioMetrico Integrado)");

    lv_obj_add_event_cb(ui_Tela_Inicial, ui_event_Tela_Inicial, LV_EVENT_ALL, NULL);

}

void ui_Tela_Inicial_screen_destroy(void)
{
    if(ui_Tela_Inicial) lv_obj_del(ui_Tela_Inicial);

    // NULL screen variables
    ui_Tela_Inicial = NULL;
    ui_Titulo = NULL;

}
