// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui_mbi

#ifndef UI_TELA_INICIAL_H
#define UI_TELA_INICIAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Inicial
extern void ui_Tela_Inicial_screen_init(void);
extern void ui_Tela_Inicial_screen_destroy(void);
extern void ui_event_Tela_Inicial(lv_event_t * e);
extern lv_obj_t * ui_Tela_Inicial;
extern lv_obj_t * ui_Titulo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

